### ISSUE TITLE
1.x for browser, 3.x for ..??

### ISSUE THREAD

**Issue by fresheneesz** [jden/objectid#2]
The readme says:

"1.x is probably the version you want to use in a browser. 3.x focuses on compatibility with the npm mongodb driver."

Are you really saying version 3.x should *not* be used in browsers? When you say "compatibility with the npm mongodb driver", what does this mean? Are you saying the interface is the same, or are you saying they should interoperate somehow?

**Comment by fresheneesz** [comment]
@jden I really wouldn't close this without doing something about it. If this is really necessary, you should have two different files in the latest version of your module - one for node and one for browser. Telling people to use an older version for browsers is pretty much the most confusing way you could handle this.

**Comment by jden** [comment]
I would gladly accept a pull request - the approach in #3 seems reasonable. Unfortunately, I don't have the time to do it myself right now.
